apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: argocd
data:
  victoria-metrics.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        uid: victoria-metrics
        access: proxy
        url: http://victoria-metrics:8428
        isDefault: true
        editable: false
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki.monitoring.svc:3100
        editable: false
