apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/clustersecretstore.yaml
  - resources/clustersecretstore-kubernetes-cnpg.yaml
  - resources/externalsecret-onepassword.yaml
  - resources/eso-stagger-refresh.yaml
