{
 "title": "MikroTik MKTXP",
 "description": "Mikrotik MKTXP Exporter metrics",
 "tags": [
  "mikrotik",
  "dashboard",
  "mktxp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(mktxp_system_identity_info, routerboard_address)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{version}} ",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "(1 - mktxp_system_free_memory{routerboard_address=\"$node\"} / mktxp_system_total_memory{routerboard_address=\"$node\"})*100",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used RAM Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - mktxp_system_free_hdd_space{routerboard_address=\"$node\"} / mktxp_system_total_hdd_space{routerboard_address=\"$node\"})*100",
     "legendFormat": "HDD Utilization"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"} - mktxp_system_free_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_system_routerboard_temperature{routerboard_address=\"$node\"}  "
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_routerboard_voltage{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "DHCP Leases by Server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "mktxp_dhcp_lease_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total DHCP Leases",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sum(mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_tx_byte_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Ethernet Ports status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mktxp_interface_status{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface  rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "mktxp_interface_rate{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_interface_rx_error_total{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "InErrors {{name}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_interface_tx_error_total{routerboard_address=\"$node\"}",
     "legendFormat": "Out Errors {{name}}"
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Overall Tx CCQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_overall_tx_ccq{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Noise Floor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_noise_floor{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Registered Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mktxp_wlan_noise_floor{routerboard_address=\"$node\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "CAPsMAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Remote Caps",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mktxp_capsman_remote_caps_info{routerboard_address=\"$node\"}",
     "legendFormat": "{{identity}}"
    }
   ]
  },
  {
   "title": "CAPsMAN Registerd Clients",
   "type": "table",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "mktxp_capsman_registered_devices_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "CAPsMAN Registrations",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_registrations_count{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(mktxp_capsman_registrations_count{routerboard_address=\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Registered Client Signal Strength",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_registered_signal_strength{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Registered Client Signal Strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_registered_signal_strength{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Registered Client Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_traffic_tx_bytes_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_traffic_rx_bytes_total{routerboard_address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}