apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vector-credentials
    creationPolicy: Owner
  data:
    - secretKey: LOKI_ENDPOINT
      remoteRef:
        key: secret/data/vector
        property: loki_endpoint
    - secretKey: LOKI_USERNAME
      remoteRef:
        key: secret/data/vector
        property: loki_username
    - secretKey: LOKI_API_KEY
      remoteRef:
        key: secret/data/vector
        property: loki_api_key
