apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root-user
  annotations:
    policies.kyverno.io/title: Require Non-Root User
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Containers must run as a non-root user. This policy ensures runAsNonRoot is set to
      true. A known issue prevents a policy such as this using 'anyPattern' from being
      persisted properly in kubectl 1.23.0-1.23.2.
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-containers
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Containers must run as non-root user."
      anyPattern:
      - spec:
          securityContext:
            runAsNonRoot: "true"
      - spec:
          containers:
          - name: "*"
            securityContext:
              runAsNonRoot: "true"
