apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - resources/namespace.yaml
  - resources/nfs.yaml
  - resources/deployment.yaml
  - resources/loki.yaml
  - resources/alloy.yaml
  - resources/grafana-pdc-agent.yaml
  - resources/ingressroute.yaml
  - resources/kube-state-metrics.yaml
  - resources/node-exporter.yaml
  - resources/victoria-metrics-rbac.yaml
  - resources/mktxp.yaml
