apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/namespace.yaml
  - resources/externalsecret.yaml
  - resources/database.yaml
  - resources/postgres-headless.yaml
  - resources/mosquitto.yaml
  - resources/hass.yaml
  - resources/zigbee2mqtt-wifi.yaml
  - resources/zigbee2mqtt-usb.yaml
  - resources/timemachine.yaml
  - resources/ingressroute.yaml
