apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: ArgoCD Project for self-management
  sourceRepos:
    - https://github.com/s3lcsum/gitops.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: argocd-admin
      description: Full access to ArgoCD project
      policies:
        - p, proj:argocd:argocd-admin, *, *, *, allow
      groups: []
