apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  description: Homelab Project for infrastructure and applications
  sourceRepos:
    - https://github.com/s3lcsum/gitops.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: homelab-admin
      description: Full access to homelab project
      policies:
        - p, proj:homelab:homelab-admin, *, *, *, allow
      groups: []
