apiVersion: v1
kind: Service
metadata:
  name: origin-proxmox
  namespace: cilium
spec:
  ports:
    - name: origin
      port: 8006
      targetPort: 8006
      appProtocol: https
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: origin-proxmox
  namespace: cilium
  labels:
    kubernetes.io/service-name: origin-proxmox
addressType: IPv4
ports:
  - name: origin
    port: 8006
    protocol: TCP
    appProtocol: https
endpoints:
  - addresses:
      - 192.168.89.254
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: origin-proxmox-ca
  namespace: cilium
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE7zCCAtegAwIBAgIBATANBgkqhkiG9w0BAQsFADB2MSQwIgYDVQQDDBtQcm94
    bW94IFZpcnR1YWwgRW52aXJvbm1lbnQxLTArBgNVBAsMJDg3NzcwNjMzLTk3MmMt
    NDM0MS04N2E2LWU0NzgzOTc3YTMwYjEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFu
    YWdlciBDQTAeFw0yNTA4MTgxNjAzMjFaFw0yNzA4MTgxNjAzMjFaMFUxGTAXBgNV
    BAsTEFBWRSBDbHVzdGVyIE5vZGUxJDAiBgNVBAoTG1Byb3htb3ggVmlydHVhbCBF
    bnZpcm9ubWVudDESMBAGA1UEAxMJbGFrZS5ob21lMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEA83UPXMSfS8Wn/0WIt+E8Dx4ShENnkNryeSN+ghCD+ME7
    /X/pxRbGQm0C2LzUsEEgwJ+Ie8rYX5aIBwMYLdq+9KAlqehMSf5ISogKsuCyFWHj
    fpirA4pdiP89ww4Fp0Peqlau8qHktoto2ve6jzZgL1gXb5cVlIxLf6pUYGSpJmbe
    vXNILCdK22zceB+rw3elYk7HcmIC8c6RUuQLO+ApRUJHfXcBGZu3dIub45f5BshR
    D5SMT7uU8HGN0nZWCV892WOEBEDPNdoEPNYNNLa3v95H1USN1pLXX46q6ZAE6Hqo
    bdFtn4TCeoG7GnD5Z+8v56ylJ6OfrGaNgX/Oy41ojQIDAQABo4GoMIGlMAkGA1Ud
    EwQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwQwYDVR0RBDwwOocEfwAAAYcQAAAA
    AAAAAAAAAAAAAAAAAYIJbG9jYWxob3N0hwTAqFncggRsYWtlgglsYWtlLmhvbWUw
    HQYDVR0OBBYEFDmyH2tssrA3My5D7ixJYpFQsJUCMB8GA1UdIwQYMBaAFMHt/lRu
    rPXieXHNsWCuCf5ZYqTcMA0GCSqGSIb3DQEBCwUAA4ICAQBMQQH7hKLOJcLxM4CB
    f/8dr2pbYZHi0Dvs1RggNpu3nhi+Lhv0GwYQcMz8Vhuzb0Q5+C38GsQxgVhPFRzm
    +XfuRmXbGkw75kxp6zSfjv5Q7soqAsebF5rqxqH6tpKHw8fjLpwxgn/96JCbcE2f
    1I0zaAQN53bKe3LD8BifkCorbrUYz6eBZKX8tVHOhodRUa22VdF+cm7joz8X0RNt
    yCXqYLqL/p/WbYM0EdAL9vpn7HirL4SoSkFZw3EN93XXMryVIpJSv7RXVRbR0Yn0
    eW3s3E1k12CgLDRjEySC4uR09qq8s/4WO8/12gfY9KAcZjVy0j/2iwOJ3LXfHteC
    gk+MfdBZP0t0JD3Uh61lxgTQfAU+WMmUBc/lYcWmkyBZlpyzOuIuYH+GUooU5giL
    N0N1BtEuUf3/5KmC4t2H6QV7URf1WU1y8C1Wfu7qolOQc1DNyMgf1tcltHw2h06F
    4HeZaPndbhi971m4sQeCDk24b+4MOZU4ZRHKv4LaXbh64dwtyAYsD11l5CDwmw3w
    RvwZmza5al1lskHTTBafZHaZdnKeD6ICX9Vd0n1epVwYh0l0aCozEJYOmbj6A4Dh
    tHQerBmtvX1xS3J3kSEsjv9RBo2++Iff7YgMHZbFIgQNziuY+O3dybdJhSjj/wWl
    YjrwAs4ughRHr+lK/M0p/zzFKA==
    -----END CERTIFICATE-----
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: origin-proxmox
  namespace: cilium
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: origin-proxmox
  validation:
    hostname: lake.home
    caCertificateRefs:
      - group: ''
        kind: ConfigMap
        name: origin-proxmox-ca
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: origin-proxmox
  namespace: cilium
spec:
  parentRefs:
    - name: cilium
      sectionName: https
  hostnames:
    - proxmox.dominiksiejak.pl
  rules:
    - backendRefs:
        - name: origin-proxmox
          port: 8006
