x-defaults: &defaults
  restart: unless-stopped
  networks:
    - monitoring
    - victoria

networks:
  monitoring:
    external: true
  victoria:
    driver: bridge

services:
  victoria-metrics:
    <<: *defaults
    image: victoriametrics/victoria-metrics
    container_name: victoria_metrics
    ports:
      - "8428:8428"
      - "4242:4242"
    volumes:
      - /portainer/Files/AppData/Config/victoria-metrics/data:/victoria-metrics-data

  victoria-logs:
    <<: *defaults
    image: victoriametrics/victoria-logs
    container_name: victoria_logs
    ports:
      - "9428:9428"
    volumes:
      - /portainer/Files/AppData/Config/victoria-logs/data:/victoria-logs-data

  vmagent:
    <<: *defaults
    image: victoriametrics/vmagent
    container_name: vmagent
    ports:
      - "8429:8429"
    volumes:
      - ./vmagent.yaml:/etc/vmagent/vmagent.yaml
    command:
      - '-promscrape.config=/etc/vmagent/vmagent.yaml'
      - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'