apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/certificate.yaml
  - resources/externalsecret-crowdsec.yaml
  - resources/backends/authentik.yaml
  - resources/backends/crowdsec-lapi.yaml
  - resources/middlewares/authentik.yaml
  - resources/middlewares/secure-headers.yaml
  - resources/middlewares/lan-only.yaml
  - resources/middlewares/crowdsec.yaml
