# github.com/s3lcsum/gitops/stacks/zitadel/compose.yaml

services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:latest
    container_name: zitadel
    user: "0"
    env_file:
      - /opt/zitadel/zitadel.env
    environment:
      # Public exposure via Traefik
      ZITADEL_EXTERNALDOMAIN: zitadel.wally.dominiksiejak.pl
      ZITADEL_EXTERNALSECURE: true # Handled by traefik
      ZITADEL_TLS_ENABLED: false

      # Login v2 configuration
      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /opt/zitadel/login-client.pat
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM_LOGIN_CLIENT
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: '2029-01-01T00:00:00Z'
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: true
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: https://zitadel.wally.dominiksiejak.pl/ui/v2/login
      ZITADEL_OIDC_DEFAULTLOGINURLV2: https://zitadel.wally.dominiksiejak.pl/ui/v2/login/login?authRequest=
      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: https://zitadel.wally.dominiksiejak.pl/ui/v2/login/logout?post_logout_redirect=
      ZITADEL_SAML_DEFAULTLOGINURLV2: https://zitadel.wally.dominiksiejak.pl/ui/v2/login/login?samlRequest=

      ZITADEL_LOG_LEVEL: debug
      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: true

    command: ["start-from-init", "--masterkeyFromEnv"]

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

    volumes:
      - zitadel_data:/opt/zitadel

    networks:
      - proxy
      - database

    labels:
      traefik.enable: "true"

  login:
    image: ghcr.io/zitadel/zitadel-login:latest
    container_name: zitadel-login
    user: "0"
    environment:
      ZITADEL_API_URL: http://localhost:8080
      NEXT_PUBLIC_BASE_PATH: /ui/v2/login
      ZITADEL_SERVICE_USER_TOKEN_FILE: /opt/zitadel/login-client.pat
    network_mode: service:zitadel
    volumes:
      - zitadel_data:/opt/zitadel:ro
    depends_on:
      zitadel:
        condition: service_healthy
        restart: false

networks:
  database:
    external: true
  proxy:
    external: true

volumes:
  zitadel_data:
