apiVersion: v2
name: intel-device-plugin
version: 0.1.0
description: Intel GPU device plugin for Jellyfin / Calibre hardware transcoding
dependencies:
  - name: intel-device-plugins-gpu
    version: "0.31.1"
    repository: "https://intel.github.io/helm-charts"
