# https://github.com/s3lcsum/gitops/blob/main/stacks/vaultwarden/compose.yaml

services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.36.0
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - /opt/vaultwarden/vaultwarden.env
    environment:
      DOMAIN: https://vaultwarden.dominiksiejak.pl
      LOG_LEVEL: warn
    volumes:
      - data:/data
    networks:
      - proxy
      - database
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: true
      homepage.group: Security
      homepage.name: Vaultwarden
      homepage.icon: vaultwarden

networks:
  proxy:
    external: true
  database:
    external: true

volumes:
  data:
