apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: vpn-gateway
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.qbittorrent.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: vpn-gateway
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.sabnzbd.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: prowlarr
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: flaresolverr
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: radarr
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: sonarr
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: bazarr
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: jellyfin
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
spec:
  selector:
    app.kubernetes.io/name: mediabox
    app.kubernetes.io/component: seerr
  ports:
    - name: http
      port: 80
      targetPort: http
