# Grafana Synthetic Monitoring Agent Configuration using official Helm chart
synthetic-monitoring-agent:
  # Image configuration
  image:
    repository: grafana/synthetic-monitoring-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent

  # Deployment configuration
  replicaCount: 1

  # Service configuration
  service:
    type: ClusterIP
    port: 4050
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "4050"
      prometheus.io/path: "/metrics"

  # Synthetic Monitoring configuration
  config:
    # API server address for your region (EU West)
    apiServerAddress: "synthetic-monitoring-grpc-eu-west.grafana.net:443"

    # Listen address for metrics endpoint
    listenAddress: "0.0.0.0:4050"

    # Log level
    logLevel: "info"

    # Enable verbose logging
    verbose: false

  # Secret configuration for API token
  secret:
    create: true
    name: ""
    # API token will be set via external secret or values
    apiToken: ""

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    capabilities:
      drop:
        - ALL

  # Pod security context
  podSecurityContext:
    fsGroup: 65534

  # Tolerations for IPv6-only nodes
  tolerations:
    - key: "node.kubernetes.io/ipv6-only"
      operator: "Exists"
      effect: "NoSchedule"

  # Node selector
  nodeSelector: {}

  # Affinity
  affinity: {}

  # Pod annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4050"
    prometheus.io/path: "/metrics"

  # Pod labels
  podLabels: {}

  # Service account
  serviceAccount:
    create: true
    annotations: {}
    name: ""

  # Probes
  livenessProbe:
    httpGet:
      path: /metrics
      port: 4050
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /metrics
      port: 4050
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  # ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: true
    labels: {}
    annotations: {}
    interval: 30s
    scrapeTimeout: 10s

  # Network policy
  networkPolicy:
    enabled: false

# External secret configuration (optional)
externalSecret:
  enabled: false
  secretStore: ""
  refreshInterval: "1h"
  data:
    - secretKey: api-token
      remoteRef:
        key: grafana-synthetic-monitoring
        property: api-token
