image:
  repository: fireflyiii/core
  tag: latest
  pullPolicy: Always

replicas: 1

env:
  APP_URL: https://money.lake.dominiksiejak.pl
  APP_ENV: production
  APP_DEBUG: "false"
  SITE_OWNER: admin@dominiksiejak.pl
  TRUSTED_PROXIES: "*"
  LOG_CHANNEL: stdout

persistence:
  size: 1Gi

hostnames:
  - money.lake.dominiksiejak.pl
