apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-data
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: n8n
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/k8s/n8n/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: n8n-data
  resources:
    requests:
      storage: 10Gi
