{{- if not .Values.n8n.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: n8n-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  encryption-key: {{ randAlphaNum 32 | quote }}
{{- end }}
