apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: gitea-data
  resources:
    requests:
      storage: 50Gi
