# 1Password vault Servers. Tag: ArgoCD External Secrets Operator
# Item grafana. Fields: synthetic-api-token, synthetic-api-server.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-synthetic-agent
  namespace: grafana-synthetic-agent
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-synthetic-agent
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: grafana/synthetic-api-token
    - secretKey: API_SERVER
      remoteRef:
        key: grafana/synthetic-api-server
