# 1Password vault Servers. Tag: ArgoCD External Secrets Operator
# Item grafana-synthetic-agent. Fields: API_TOKEN, API_SERVER.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-synthetic-agent
  namespace: grafana-synthetic-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-synthetic-agent
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: grafana-synthetic-agent/API_TOKEN
    - secretKey: API_SERVER
      remoteRef:
        key: grafana-synthetic-agent/API_SERVER
