# Alloy Stack
# Exposes metrics and logs to Grafana Cloud
# Maintainer: Dominik Siejak

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    networks:
      - metrics
      - proxy
    env_file:
      - /Portainer/alloy/.env
    environment:
      PROM_REMOTE_WRITE_URL: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
      LOKI_WRITE_URL: "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - /Portainer/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /run/log/journal:/run/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy.rule=Host(`alloy.wally.dominiksiejak.pl`)"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.middlewares=secure-headers@file,rate-limit@file"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"


networks:
  metrics:
    external: true
  proxy:
    external: true
