apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops
  namespace: argocd
  labels:
    app.kubernetes.io/name: sops
    app.kubernetes.io/part-of: sops
spec:
  project: default
  source:
    repoURL: https://github.com/s3lcsum/gitops.git
    targetRevision: main
    path: kubernetes/sops
    helm:
      releaseName: sops
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
