apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-alloy-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-alloy-credentials
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLOUD_PROMETHEUS_URL
      remoteRef:
        key: secret/data/grafana-alloy
        property: prometheus_remote_write_url
    - secretKey: GRAFANA_CLOUD_USERNAME
      remoteRef:
        key: secret/data/grafana-alloy
        property: prometheus_username
    - secretKey: GRAFANA_CLOUD_API_KEY
      remoteRef:
        key: secret/data/grafana-alloy
        property: api_key
