# HomePage Complete Configuration
# Combined settings, services, bookmarks, and docker configuration

# Settings
title: "Wally Home Lab"
favicon: /icons/favicon.ico

background:
  image: /images/background.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

theme: dark # light, dark
color: slate # slate, gray, zinc, neutral, stone, red, orange, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose
target: _blank # optional, defaults to _self
language: en

layout:
  - Monitoring:
      style: row
      columns: 3
  - Media:
      style: row
      columns: 3
  - Security:
      style: row
      columns: 2
  - Database:
      style: row
      columns: 2
  - Automation:
      style: row
      columns: 2
  - System:
      style: row
      columns: 3
  - Network:
      style: row
      columns: 2
  - VPN:
      style: row
      columns: 2

headerStyle: boxed # boxed, underlined, clean
hideVersion: true

# Docker Configuration
providers:
  docker:
    socket: /var/run/docker.sock

# Services Configuration
services:
  # Monitoring
  - Monitoring:
      - Alloy:
          icon: grafana.png
          href: https://alloy.wally.dominiksiejak.pl
          description: Grafana Alloy - Metrics and logs collection
          container: alloy
          server: docker

      - Dozzle:
          icon: dozzle.png
          href: https://dozzle.wally.dominiksiejak.pl
          description: Real-time log viewer for Docker containers
          container: dozzle
          server: docker

      - Uptime Kuma:
          icon: uptime-kuma.png
          href: https://uptime.wally.dominiksiejak.pl
          description: Uptime monitoring and status page
          container: uptime-kuma
          server: docker

  # Media
  - Media:
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.wally.dominiksiejak.pl
          description: Media server for streaming movies and TV shows
          container: jellyfin
          server: docker

      - Jellyseerr:
          icon: overseerr.png
          href: https://jellyseerr.wally.dominiksiejak.pl
          description: Request management for Jellyfin media server
          container: jellyseerr
          server: docker

      - Radarr:
          icon: radarr.png
          href: https://radarr.wally.dominiksiejak.pl
          description: Movie collection management and automation
          container: radarr
          server: docker

      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.wally.dominiksiejak.pl
          description: TV series collection management and automation
          container: sonarr
          server: docker

      - Bazarr:
          icon: bazarr.png
          href: https://bazarr.wally.dominiksiejak.pl
          description: Subtitle management for media files
          container: bazarr
          server: docker

      - Lidarr:
          icon: lidarr.png
          href: https://lidarr.wally.dominiksiejak.pl
          description: Music collection management and automation
          container: lidarr
          server: docker

  # Security
  - Security:
      - Authentik:
          icon: authentik.png
          href: https://auth.wally.dominiksiejak.pl
          description: Identity provider and authentication platform
          container: authentik
          server: docker

  # Database
  - Database:
      - Adminer:
          icon: adminer.png
          href: https://adminer.wally.dominiksiejak.pl
          description: Database management tool for PostgreSQL
          container: adminer
          server: docker

  # Automation
  - Automation:
      - n8n:
          icon: n8n.png
          href: https://nodemation.wally.dominiksiejak.pl
          description: Workflow automation platform
          container: n8n
          server: docker

  # System
  - System:
      - CUPS:
          icon: cups.png
          href: https://cups.wally.dominiksiejak.pl
          description: Print server for managing printers and print jobs
          container: cups
          server: docker

      - Netboot.xyz:
          icon: netbootxyz.png
          href: https://netboot.wally.dominiksiejak.pl
          description: Network boot server for PXE booting
          container: netbootxyz
          server: docker

      - Upsnap:
          icon: upsnap.png
          href: https://upsnap.wally.dominiksiejak.pl
          description: Wake-on-LAN and power management for network devices
          container: upsnap
          server: docker

  # Network
  - Network:
      - WatchYourLAN:
          icon: watchyourlan.png
          href: https://lan.wally.dominiksiejak.pl
          description: Network device discovery and monitoring
          container: watchyourlan
          server: docker

  # VPN
  - VPN:
      - Gluetun:
          icon: gluetun.png
          href: https://qbittorrent.wally.dominiksiejak.pl
          description: VPN gateway for secure torrenting
          container: gluetun
          server: docker

# Bookmarks Configuration
bookmarks:
  - Infrastructure:
      - Synology NAS:
          - icon: synology-dsm.png
            href: https://synology.wally.dominiksiejak.pl
            description: Network-attached storage management
      - Proxmox:
          - icon: proxmox.png
            href: https://proxmox.wally.dominiksiejak.pl
            description: Virtualization platform
      - MikroTik Router:
          - icon: mikrotik.png
            href: https://router.wally.dominiksiejak.pl
            description: Network router configuration

  - Development:
      - GitHub:
          - icon: github.png
            href: https://github.com/s3lcsum/gitops
            description: GitOps repository
      - Grafana Cloud:
          - icon: grafana.png
            href: https://grafana.com
            description: Monitoring and observability

  - External Services:
      - Cloudflare:
          - icon: cloudflare.png
            href: https://dash.cloudflare.com
            description: DNS and CDN management
      - Portainer:
          - icon: portainer.png
            href: https://portainer.io
            description: Container management platform
