# K3s IPv6-Only Configuration
# Place this file at /etc/rancher/k3s/config.yaml on your K3s nodes

# Cluster configuration
cluster-init: true
token: "your-cluster-token-here"

# IPv6-only networking
cluster-cidr: "fd89:4::/48"
service-cidr: "fd89:5::/112"
cluster-dns: "fd89:5::10"

# Disable IPv4
disable-network-policy: false
flannel-ipv6-masq: true
flannel-backend: "host-gw"

# Node configuration
node-ip: "fd89:2::100"  # Update for each node
node-external-ip: "fd89:2::100"  # Update for each node

# API server configuration
bind-address: "::"
https-listen-port: 6443
advertise-address: "fd89:2::100"  # Update for each node

# Kubelet configuration
kubelet-arg:
  - "node-ip=fd89:2::100"  # Update for each node
  - "cluster-dns=fd89:5::10"
  - "cluster-domain=cluster.local"

# Kube-proxy configuration
kube-proxy-arg:
  - "bind-address=::"
  - "cluster-cidr=fd89:4::/48"

# Disable components we don't need
disable:
  - traefik  # We'll use our own ingress
  - servicelb  # We'll use MetalLB for IPv6

# Enable required features
kube-apiserver-arg:
  - "service-cluster-ip-range=fd89:5::/112"
  - "bind-address=::"
  - "advertise-address=fd89:2::100"  # Update for each node

kube-controller-manager-arg:
  - "bind-address=::"
  - "cluster-cidr=fd89:4::/48"
  - "service-cluster-ip-range=fd89:5::/112"

kube-scheduler-arg:
  - "bind-address=::"

# Etcd configuration for IPv6
etcd-arg:
  - "listen-client-urls=https://[::]:2379"
  - "listen-peer-urls=https://[fd89:2::100]:2380"  # Update for each node
  - "advertise-client-urls=https://[fd89:2::100]:2379"  # Update for each node
