apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - application-coredns.yaml
  - application-hass.yaml
  - applicationset.yaml
  - externalsecret-oidc.yaml
  - externalsecret-repo-creds.yaml
  - ingressroute.yaml
