# https://github.com/s3lcsum/gitops/blob/main/stacks/cloudflared/compose.yaml

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.2
    container_name: cloudflared
    restart: unless-stopped
    env_file:
      - /opt/cloudflared/cloudflared.env
    networks:
      - proxy
    command: tunnel run

networks:
  proxy:
    external: true
