apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: error-pages
resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/middleware.yaml
  - resources/ingressroute.yaml
