apiVersion: v2
name: grafana-agent
description: Grafana Agent for collecting metrics and logs to Grafana Cloud
type: application
version: 0.1.0
appVersion: "0.38.1"

dependencies:
- name: grafana-agent
  version: "0.25.0"
  repository: https://grafana.github.io/helm-charts
