---
# Bookmarks — quick links
# Icons: https://github.com/walkxcode/dashboard-icons

- DevOps:
    - GitHub:
        - url: https://github.com/s3lcsum
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/github.png

    - Cloudflare:
        - url: https://dash.cloudflare.com
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/cloudflare.png
