services:
  nginx-proxy:
    container_name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - nginx-proxy-data:/data
      - nginx-proxy-letsencrypt:/etc/letsencrypt
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 3s

volumes:
  nginx-proxy-data:
  nginx-proxy-letsencrypt:
