apiVersion: v2
name: reloader
version: 0.1.0
description: Stakater Reloader — roll pods when referenced ConfigMaps or Secrets change
dependencies:
  - name: reloader
    version: "2.2.9"
    repository: "https://stakater.github.io/stakater-charts"
