services:
  uptime_kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - "3002:3001"
    volumes:
      - uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  uptime-kuma-data:
