# MKTXP Stack
# Mikrotik Prometheus exporter
# Maintainer: Dominik Siejak

services:
  mktxp:
    image: ghcr.io/akpw/mktxp:1.2.0
    container_name: mktxp
    restart: unless-stopped
    networks:
      - metrics
    volumes:
      - /Portainer/mktxp/mktxp.conf:/root/mktxp/mktxp.conf
    healthcheck:
      test: ["CMD", "mktxp", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  metrics:
    external: true
