# MKTXP Stack
# Mikrotik Prometheus exporter
# Maintainer: Dominik Siejak

services:
  mktxp:
    image: ghcr.io/akpw/mktxp:latest
    container_name: mktxp
    restart: unless-stopped
    networks:
      - metrics
    volumes:
      - /Portainer/mktxp/mktxp.conf:/root/mktxp/mktxp.conf


networks:
  metrics:
    external: true
