apiVersion: v2
name: metallb
version: 0.1.0
description: MetalLB load-balancer for bare-metal / homelab clusters
dependencies:
  - name: metallb
    version: "0.14.9"
    repository: "https://metallb.github.io/metallb"
