apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflared-credentials
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: secret/data/cloudflared
        property: tunnel-token
