# https://github.com/s3lcsum/gitops/blob/main/stacks/dozzle/compose.yaml

services:
  dozzle:
    image: ghcr.io/amir20/dozzle:v10.6.5
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.middlewares: authentik@docker

networks:
  proxy:
    external: true
