apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediabox
resources:
  - resources/namespace.yaml
  - resources/gluetun.yaml
  - resources/apps.yaml
  - resources/ingressroute.yaml
