x-default: &default
  restart: unless-stopped
  environment:
    TZ: Europe/Warsaw
services:
  hass:
    <<: *default
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass
    depends_on:
      - mosquitto
    volumes:
      - data:/config
    network_mode: host # Otherwise autodiscovery won't work
    labels:
      traefik.enable: true
      traefik.http.routers.hass.rule: Host(`hass.lake.dominiksiejak.pl`) || Host(`hass.hello.dominiksiejak.pl`)
      traefik.http.services.hass.loadbalancer.server.url: http://192.168.89.253:8123

  zigbee2mqtt:
    <<: *default
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - zigbee2mqtt_data:/app/data
      - /opt/hass/zigbee2mqtt.yaml:/app/data/configuration.yaml
    networks:
      - proxy
    extra_hosts:
      - "mosquitto:host-gateway"
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.lake.dominiksiejak.pl`)
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080
      traefik.http.routers.zigbee2mqtt.middlewares: authentik@docker

  mosquitto:
    <<: *default
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - /opt/hass/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
    network_mode: host # Because home-assistant have to be on the same network as the coordinator

  esphome:
    <<: *default
    image: ghcr.io/esphome/esphome:stable
    container_name: esphome
    privileged: true
    network_mode: host # Autodiscovery won't work otherwise
    volumes:
      - esphome_data:/config
    labels:
      traefik.enable: true
      traefik.http.routers.esphome.rule: Host(`esphome.lake.dominiksiejak.pl`)
      traefik.http.services.esphome.loadbalancer.server.url: http://192.168.89.253:6052

networks:
  proxy:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/homeassistant
      o: bind
  zigbee2mqtt_data:
  mosquitto_data:
  esphome_data:
