# 1Password vault Servers. Tag: ArgoCD External Secrets Operator
# Items: hass-mosquitto/passwd, hass-mqtt/username, hass-mqtt/password,
# hass-timemachine/LONG_LIVED_ACCESS_TOKEN, hass-database/password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-mosquitto
  namespace: hass
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hass-mosquitto
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: passwd
      remoteRef:
        key: hass-mosquitto/passwd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-mqtt
  namespace: hass
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hass-mqtt
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: username
      remoteRef:
        key: hass-mqtt/username
    - secretKey: password
      remoteRef:
        key: hass-mqtt/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-timemachine
  namespace: hass
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hass-timemachine
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: LONG_LIVED_ACCESS_TOKEN
      remoteRef:
        key: hass-timemachine/LONG_LIVED_ACCESS_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-user
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: hass-user
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
      data:
        username: hass_user
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: hass-database/password
