apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken | quote }}
