apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/component: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: calibre-web
          image: "{{ .Values.calibreWeb.image.repository }}:{{ .Values.calibreWeb.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.calibreWeb.port }}
          env:
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Europe/Warsaw
          volumeMounts:
            - name: config
              mountPath: /config
            - name: books
              mountPath: /books
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: books
          hostPath:
            path: {{ .Values.nfs.localMedia }}
            type: DirectoryOrCreate
