apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.calibreConfig.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.calibreWebConfig.size }}
