apiVersion: v1
kind: PersistentVolume
metadata:
  name: watchyourlan-data
  labels:
    app.kubernetes.io/name: watchyourlan
    app.kubernetes.io/part-of: watchyourlan
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/k8s/watchyourlan/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watchyourlan-data
  namespace: watchyourlan
  labels:
    app.kubernetes.io/name: watchyourlan
    app.kubernetes.io/part-of: watchyourlan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: watchyourlan-data
  resources:
    requests:
      storage: 1Gi
