{
 "title": "Synology Disks",
 "tags": [
  "dsm",
  "snmp",
  "synology",
  "disk"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(modelName, job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(modelName, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskTemperature{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskHealthStatus{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Bad Sectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskBadSector{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Temperature Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Load % (1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "storageIOLA1{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Read (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(storageIONReadX{job=~\"$job\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Disk Write (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(storageIONWrittenX{job=~\"$job\"}[$__rate_interval])"
    }
   ]
  }
 ]
}