apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: watchyourlan
resources:
  - resources/namespace.yaml
  - resources/nfs.yaml
  - resources/deployment.yaml
  - resources/ingressroute.yaml
