# 1Password vault Servers. Tag: ArgoCD External Secrets Operator
# Item: adguard / username, password
# URL is not secret: AdGuard hostNetwork on the lake node.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: adguard
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: username
      remoteRef:
        key: adguard/username
    - secretKey: password
      remoteRef:
        key: adguard/password
