apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-datasources
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-cloud-datasources
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        zz-grafana-cloud.yaml: |
          apiVersion: 1
          datasources:
            - name: Grafana Cloud Prometheus
              type: prometheus
              uid: grafana-cloud-prom
              url: "{{ "{{ .prometheus_query_url }}" }}"
              access: proxy
              isDefault: false
              editable: false
              basicAuth: true
              basicAuthUser: "{{ "{{ .prometheus_username }}" }}"
              secureJsonData:
                basicAuthPassword: "{{ "{{ .api_key }}" }}"
            - name: Grafana Cloud Loki
              type: loki
              uid: grafana-cloud-loki
              url: "{{ "{{ .loki_query_url }}" }}"
              access: proxy
              editable: false
              basicAuth: true
              basicAuthUser: "{{ "{{ .prometheus_username }}" }}"
              secureJsonData:
                basicAuthPassword: "{{ "{{ .api_key }}" }}"
  data:
    - secretKey: prometheus_query_url
      remoteRef:
        key: secret/data/grafana-alloy
        property: prometheus_query_url
    - secretKey: prometheus_username
      remoteRef:
        key: secret/data/grafana-alloy
        property: prometheus_username
    - secretKey: api_key
      remoteRef:
        key: secret/data/grafana-alloy
        property: api_key
    - secretKey: loki_query_url
      remoteRef:
        key: secret/data/grafana-alloy
        property: loki_query_url
