apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-password: "{{ "{{ .password }}" }}"
        admin-user: admin
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/grafana
        property: admin_password
