apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: hass
    app.kubernetes.io/component: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: hass
      app.kubernetes.io/component: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hass
        app.kubernetes.io/component: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: "{{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}"
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          ports:
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: data
              mountPath: /mosquitto/data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
