apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.homeassistant.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.mosquitto.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.zigbee2mqtt.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.esphome.persistence.size }}
