apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-media
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/k8s/authentik/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: authentik-media
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-templates
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/k8s/authentik/templates
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: authentik-templates
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-certs
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-bind
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.89.240
    path: /volume1/media/k8s/authentik/certs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-certs
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-bind
  volumeName: authentik-certs
  resources:
    requests:
      storage: 1Gi
