# 1Password vault Servers. Tag: ArgoCD External Secrets Operator
# Item openbao. Fields oidc-client-id / oidc-client-secret from authentik tofu output.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-oidc
  namespace: openbao
spec:
  refreshPolicy: OnChange
  refreshInterval: 0s
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: openbao-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: client-id
      remoteRef:
        key: openbao/oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: openbao/oidc-client-secret
