apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@dominiksiejak.pl
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    # DNS-01 for both *.lake.* (internal, RFC1918) and *.hello.* (public).
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
