# 1Password vault Servers, item netbox. Tag: ArgoCD External Secrets Operator
# TF_API_TOKEN stays in 1Password for local tofu only — not synced into the pod Secret.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
  namespace: netbox
spec:
  refreshPolicy: OnChange
  refreshInterval: 0s
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: netbox
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels: {}
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
  data:
    - secretKey: API_TOKEN_PEPPERS
      remoteRef:
        key: netbox/API_TOKEN_PEPPERS
    - secretKey: DB_HOST
      remoteRef:
        key: netbox/DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: netbox/DB_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: netbox/DB_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: netbox/DB_USER
    - secretKey: LOGOUT_REDIRECT_URL
      remoteRef:
        key: netbox/LOGOUT_REDIRECT_URL
    - secretKey: REDIS_HOST
      remoteRef:
        key: netbox/REDIS_HOST
    - secretKey: REMOTE_AUTH_AUTO_CREATE_GROUPS
      remoteRef:
        key: netbox/REMOTE_AUTH_AUTO_CREATE_GROUPS
    - secretKey: REMOTE_AUTH_AUTO_CREATE_USER
      remoteRef:
        key: netbox/REMOTE_AUTH_AUTO_CREATE_USER
    - secretKey: REMOTE_AUTH_BACKEND
      remoteRef:
        key: netbox/REMOTE_AUTH_BACKEND
    - secretKey: REMOTE_AUTH_DEFAULT_GROUPS
      remoteRef:
        key: netbox/REMOTE_AUTH_DEFAULT_GROUPS
    - secretKey: REMOTE_AUTH_ENABLED
      remoteRef:
        key: netbox/REMOTE_AUTH_ENABLED
    - secretKey: REMOTE_AUTH_GROUP_SYNC_ENABLED
      remoteRef:
        key: netbox/REMOTE_AUTH_GROUP_SYNC_ENABLED
    - secretKey: REMOTE_AUTH_SUPERUSER_GROUPS
      remoteRef:
        key: netbox/REMOTE_AUTH_SUPERUSER_GROUPS
    - secretKey: SECRET_KEY
      remoteRef:
        key: netbox/SECRET_KEY
    - secretKey: SKIP_SUPERUSER
      remoteRef:
        key: netbox/SKIP_SUPERUSER
    - secretKey: SOCIAL_AUTH_OIDC_KEY
      remoteRef:
        key: netbox/SOCIAL_AUTH_OIDC_KEY
    - secretKey: SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
      remoteRef:
        key: netbox/SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
    - secretKey: SOCIAL_AUTH_OIDC_SCOPE
      remoteRef:
        key: netbox/SOCIAL_AUTH_OIDC_SCOPE
    - secretKey: SOCIAL_AUTH_OIDC_SECRET
      remoteRef:
        key: netbox/SOCIAL_AUTH_OIDC_SECRET
