# IPv6-Only ArgoCD Configuration

argocd:
  # Global configuration
  global:
    # Set logging format (text or json)
    logging:
      format: "json"
      level: "info"

    # IPv6-only network configuration
    networkPolicy:
      enabled: true
      defaultDenyIngress: false

  # ArgoCD Server configuration
  server:
    # Replicas for high availability
    replicas: 2

    # IPv6-only service configuration
    service:
      type: ClusterIP
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argocd.lake.dominiksiejak.pl"

    # Ingress for external access
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argocd.lake.dominiksiejak.pl"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      hosts:
        - argocd.lake.dominiksiejak.pl
      tls:
        - secretName: argocd-server-tls
          hosts:
            - argocd.lake.dominiksiejak.pl

    # IPv6 node tolerations
    tolerations:
      - key: "node.kubernetes.io/ipv6-only"
        operator: "Exists"
        effect: "NoSchedule"

  # Repository Server IPv6 configuration
  repoServer:
    service:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
    tolerations:
      - key: "node.kubernetes.io/ipv6-only"
        operator: "Exists"
        effect: "NoSchedule"

  # Application Controller IPv6 configuration
  controller:
    service:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
    tolerations:
      - key: "node.kubernetes.io/ipv6-only"
        operator: "Exists"
        effect: "NoSchedule"

  # Redis IPv6 configuration
  redis:
    service:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
    tolerations:
      - key: "node.kubernetes.io/ipv6-only"
        operator: "Exists"
        effect: "NoSchedule"

  # Enable metrics
  metrics:
    enabled: true
